apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  labels:
    app: kubernetes
    role: manager
    high-availability-config.resources.gardener.cloud/type: controller
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
      role: manager
  template:
    metadata:
      labels:
        gardener.cloud/role: controlplane
        app: kubernetes
        role: manager
    spec:
      automountServiceAccountToken: true
      hostNetwork: true
      containers:
        - name: manager
          image: controller:latest
          imagePullPolicy: IfNotPresent
          command:
            - /metal-cloud-controller-manager
          args:
            - --cloud-provider=metal
            - --concurrent-service-syncs=10
            - --leader-elect=true
            - --secure-port=10258
            - --requestheader-client-ca-file=/etc/config/ca
            - --use-service-account-credentials
            - --v=2
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTPS
              port: 10258
            successThreshold: 1
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 15
          ports:
            - containerPort: 10258
              name: metrics
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/config
              name: kube-root-ca
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      serviceAccountName: manager
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      volumes:
        - configMap:
            name: kube-root-ca.crt
            items:
              - key: ca.crt
                path: ca
          name: kube-root-ca
