apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: cloud-controller-manager
    namespace: kube-system
