apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manager
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - get
      - create
      - delete
