name: Test Chart

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Verify Helm installation
        run: helm version

      - name: Lint Helm Chart
        run: |
          helm lint ./dist/chart

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster

      - name: Prepare metal-cloud-controller
        run: |
          go mod download
          make docker-build CONTROLLER_IMG=metal-cloud-controller:v0.1.0
          kind load docker-image metal-cloud-controller:v0.1.0

      - name: Install Helm chart for project
        run: |
          helm install my-release ./dist/chart --create-namespace --namespace metal-cloud-controller-system

      - name: Check Helm release status
        run: |
          helm status my-release --namespace metal-cloud-controller-system
